/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as ApiSearchProtocolsRouteImport } from './routes/api.search-protocols'
import { Route as ApiSearchPapersRouteImport } from './routes/api.search-papers'
import { Route as ApiSearchLiteratureRouteImport } from './routes/api.search-literature'
import { Route as ApiResolveMaterialsRouteImport } from './routes/api.resolve-materials'
import { Route as ApiGeneratePlanRouteImport } from './routes/api.generate-plan'
import { Route as ApiGenerateExampleRouteImport } from './routes/api.generate-example'
import { Route as ProjectIdPresentRouteImport } from './routes/project.$id.present'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchProtocolsRoute = ApiSearchProtocolsRouteImport.update({
  id: '/api/search-protocols',
  path: '/api/search-protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchPapersRoute = ApiSearchPapersRouteImport.update({
  id: '/api/search-papers',
  path: '/api/search-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchLiteratureRoute = ApiSearchLiteratureRouteImport.update({
  id: '/api/search-literature',
  path: '/api/search-literature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveMaterialsRoute = ApiResolveMaterialsRouteImport.update({
  id: '/api/resolve-materials',
  path: '/api/resolve-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePlanRoute = ApiGeneratePlanRouteImport.update({
  id: '/api/generate-plan',
  path: '/api/generate-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateExampleRoute = ApiGenerateExampleRouteImport.update({
  id: '/api/generate-example',
  path: '/api/generate-example',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdPresentRoute = ProjectIdPresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/generate-example': typeof ApiGenerateExampleRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/api/resolve-materials': typeof ApiResolveMaterialsRoute
  '/api/search-literature': typeof ApiSearchLiteratureRoute
  '/api/search-papers': typeof ApiSearchPapersRoute
  '/api/search-protocols': typeof ApiSearchProtocolsRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/$id/present': typeof ProjectIdPresentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/generate-example': typeof ApiGenerateExampleRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/api/resolve-materials': typeof ApiResolveMaterialsRoute
  '/api/search-literature': typeof ApiSearchLiteratureRoute
  '/api/search-papers': typeof ApiSearchPapersRoute
  '/api/search-protocols': typeof ApiSearchProtocolsRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/$id/present': typeof ProjectIdPresentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/generate-example': typeof ApiGenerateExampleRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/api/resolve-materials': typeof ApiResolveMaterialsRoute
  '/api/search-literature': typeof ApiSearchLiteratureRoute
  '/api/search-papers': typeof ApiSearchPapersRoute
  '/api/search-protocols': typeof ApiSearchProtocolsRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/$id/present': typeof ProjectIdPresentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/projects'
    | '/api/generate-example'
    | '/api/generate-plan'
    | '/api/resolve-materials'
    | '/api/search-literature'
    | '/api/search-papers'
    | '/api/search-protocols'
    | '/project/$id'
    | '/project/$id/present'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/projects'
    | '/api/generate-example'
    | '/api/generate-plan'
    | '/api/resolve-materials'
    | '/api/search-literature'
    | '/api/search-papers'
    | '/api/search-protocols'
    | '/project/$id'
    | '/project/$id/present'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/projects'
    | '/api/generate-example'
    | '/api/generate-plan'
    | '/api/resolve-materials'
    | '/api/search-literature'
    | '/api/search-papers'
    | '/api/search-protocols'
    | '/project/$id'
    | '/project/$id/present'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiGenerateExampleRoute: typeof ApiGenerateExampleRoute
  ApiGeneratePlanRoute: typeof ApiGeneratePlanRoute
  ApiResolveMaterialsRoute: typeof ApiResolveMaterialsRoute
  ApiSearchLiteratureRoute: typeof ApiSearchLiteratureRoute
  ApiSearchPapersRoute: typeof ApiSearchPapersRoute
  ApiSearchProtocolsRoute: typeof ApiSearchProtocolsRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-protocols': {
      id: '/api/search-protocols'
      path: '/api/search-protocols'
      fullPath: '/api/search-protocols'
      preLoaderRoute: typeof ApiSearchProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-papers': {
      id: '/api/search-papers'
      path: '/api/search-papers'
      fullPath: '/api/search-papers'
      preLoaderRoute: typeof ApiSearchPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-literature': {
      id: '/api/search-literature'
      path: '/api/search-literature'
      fullPath: '/api/search-literature'
      preLoaderRoute: typeof ApiSearchLiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve-materials': {
      id: '/api/resolve-materials'
      path: '/api/resolve-materials'
      fullPath: '/api/resolve-materials'
      preLoaderRoute: typeof ApiResolveMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-plan': {
      id: '/api/generate-plan'
      path: '/api/generate-plan'
      fullPath: '/api/generate-plan'
      preLoaderRoute: typeof ApiGeneratePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-example': {
      id: '/api/generate-example'
      path: '/api/generate-example'
      fullPath: '/api/generate-example'
      preLoaderRoute: typeof ApiGenerateExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/present': {
      id: '/project/$id/present'
      path: '/present'
      fullPath: '/project/$id/present'
      preLoaderRoute: typeof ProjectIdPresentRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdPresentRoute: typeof ProjectIdPresentRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdPresentRoute: ProjectIdPresentRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  ApiGenerateExampleRoute: ApiGenerateExampleRoute,
  ApiGeneratePlanRoute: ApiGeneratePlanRoute,
  ApiResolveMaterialsRoute: ApiResolveMaterialsRoute,
  ApiSearchLiteratureRoute: ApiSearchLiteratureRoute,
  ApiSearchPapersRoute: ApiSearchPapersRoute,
  ApiSearchProtocolsRoute: ApiSearchProtocolsRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
